spring:
  application:
    name: select-front
  session:
    store-type: redis  # Redis를 세션 저장소로 사용
    redis:
      host: localhost  # Redis 서버 호스트
      port: 6379       # Redis 서버 포트
      timeout: 10000   # Redis 연결 타임아웃 (밀리초 단위)
      database: 0      # 사용할 Redis 데이터베이스 번호 (기본값은 0)
    timeout: 600
  redis:
    host: localhost
    port: 6379
    timeout: 10000
    database: 0
server:
  port: 7007

feign-data:
  url: ${ORDER_SERVICE_URL:http://localhost:7010}
custom:
  login-service-url: "http://localhost:7010"

