spring:
        # 개발 중에는 캐시를 비활성화하여 템플릿 변경 시 즉시 반영되도록

server:
  port: 7007

swfm:
  select-service-url: ${SELECT_SERVICE_URL:http://localhost:7001}/select
  cart-service-url: ${CART_SERVICE_URL:http://localhost:7001}/cart
  news-list-service: ${NEWS_LIST_SERVICE_URL:http://localhost:7710}/news
  auth-url: ${auth_SERVICE_URL:http://localhost:7010}
custom:
  login-service-url: "http://localhost:7010"

user:
  api-url: http://localhost:9010  # 백엔드 API URL 설정
