spring:
  application:
    name: select-front
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 7007

swfm:
  service-url: ${SELECT_SERVICE_URL:http://localhost:9000}

user:
  api-url: http://localhost:9010  # 백엔드 API URL 설정

file:
#  upload-dir: /Users/chodaekyung/Desktop/uploads
#  upload-dir: C:/Users/jjjkk/Desktop/파이널프로젝트이미지
  upload-dir: C:/Users/admin/Desktop/uploud